### ISSUE TITLE
Error using non-debian-packages: failed to resize tty, using default size

### ISSUE THREAD

**Issue by SimonBard** [bugsyb/recognize_docker#8]
I could compile the image, but it fails when starting up:
docker run -it --rm --gpus all -v [....] --name=nextcloud-recognize local/nextcloud-recognize-gpu:latest -d

I am using a location (-v), which was used before with nextcloud.

First time I get the error:
```
/entrypoint.sh: 279: exec: -d: not found
failed to resize tty, using default size
```

When I start it a 2nd time withoug "-d", I get:
```
/entrypoint.sh: 137: cannot create /var/www/html/nextcloud-init-sync.lock: Permission denied
failed to resize tty, using default size
```

When I use a completely new location, I get:
`/entrypoint.sh: 137: cannot create /var/www/html/nextcloud-init-sync.lock: Permission denied`

**Comment by bugsyb** [comment]
Here is my docker compose yaml, hope it helps and all mappings do work without issue.
Note that it is incomplete yaml, as I do use both Redis and FPM based frontend (Nginx), which is marked here + bunch of other customization included historically for apache based and nginx:
```
  nextcloud:
    image: local/nextcloud:30-fpm-custom-tensor
    container_name: nextcloud
    hostname: nc
    cap_add:
      - SYS_PTRACE
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - POSTGRES_DB=
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST=
      - NEXTCLOUD_DATA_DIR=$NEXTCLOUD_DATA_DIR
      - NEXTCLOUD_UPLOAD_TMP_DIR=$NEXTCLOUD_DATA_DIR/upload-tmp/
      - PHP_MEMORY_LIMIT=4096M
      - PHP_UPLOAD_LIMIT=16G
      - PHP_EXECUTION_TIME=14400
      - POST_MAX_SIZE==16G
      - MAX_INPUT_TIME=14400
      - MAX_EXECUTION_TIME=14400
    volumes:
      - ${APPO}/nextcloud_var/sys_overlay/docker-entrypoint-hooks.d/:/docker-entrypoint-hooks.d/
      - ${APPO}/nextcloud_var/sys_overlay/etc/nginx/nginx-subfolder.conf:/etc/nginx/nginx.conf:ro
      - ${APPO}/nextcloud_var/sys_overlay/etc/sudoers.d/www-data-cron:/etc/sudoers.d/www-data-cron
      - ${APPO}/nextcloud_var/sys_overlay/etc/apache2/mods-enabled/mpm_prefork.conf:/etc/apache2/mods-enabled/mpm_prefork.conf:ro
      - ${APPO}/nextcloud_var/sys_overlay/usr/local/etc/php/conf.d/upload-mod.ini:/usr/local/etc/php/conf.d/upload-mod.ini:ro
      - ${APPO}/nextcloud_var/sys_overlay/usr/local/etc/php/conf.d/apc-enable-cron.ini:/usr/local/etc/php/conf.d/apc-enable-cron.ini:ro
      - ${APPO}/nextcloud_var/sys_overlay/usr/local/etc/php/conf.d/additional-fixes.ini:/usr/local/etc/php/conf.d/additional-fixes.ini:ro
      - ${APPO}/nextcloud_var/sys_overlay/usr/local/etc/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      - ${APPO}/nextcloud_var/html:/var/www/html
      - ${APPO}/nextcloud_var/config:/var/www/html/config
      - ${APPO}/nextcloud_var/recognize:/var/www/html/custom_apps/recognize
      - ${STORAGE_SHARES}/nextcloud:/data
# other mappings
#...
#
      - ${APPL}/nextcloud/:/log/

    tmpfs:
      - /var/run:rw,exec,mode=1777
      - /var/cache:rw,exec,mode=1777
      - /tmp:rw,exec,mode=1777
    networks:
      - prvcloud
      - mgmt_nout_fe
    restart: unless-stopped
    depends_on:
      - redis

```
